# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.box = "kwilczynski/ubuntu-16.04"
  config.vm.synced_folder ".", "/home/vagrant/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y install libseccomp-dev
    apt-get -y install auditd
    sudo apt-get install libssl1.1
    sudo apt-get install -y make
    sudo apt-get install -y snapd
    sudo apt-get install -y gcc
    sudo apt-get install -y g++
    sudo apt-get install -y flex
    sudo apt-get install -y bison
    sudo apt-get install -y nginx
    sudo apt-get install -y nano
    sudo apt-get install -y git
    sudo apt-get install -y mysql-client
    sudo apt-get install -y mongodb-clients
    sudo apt-get install -y apache2-utils
    sudo apt-get install -y redis
    pip3 install numpy
    pip3 install matplotlib
    pip3 install pyPDF2
    pip3 install pillow
    pip3 install pandas
    pip3 install xlrd
    pip3 install openpyxl
    sudo apt-get install -y sysdig
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io
    usermod -aG docker vagrant
    sudo apt-get install -y sysdig
    sudo snap install curl
    curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
  SHELL
  

end
